INSERT INTO institution (name, type, province, website, accreditation) VALUES
-- Public Universities
('University of Cape Town', 'University', 'Western Cape', 'https://www.uct.ac.za', 'CHE'),
('University of Fort Hare', 'University', 'Eastern Cape', 'https://www.ufh.ac.za', 'CHE'),
('University of the Free State', 'University', 'Free State', 'https://www.ufs.ac.za', 'CHE'),
('University of KwaZulu-Natal', 'University', 'KwaZulu-Natal', 'https://www.ukzn.ac.za', 'CHE'),
('University of Johannesburg', 'University', 'Gauteng', 'https://www.uj.ac.za', 'CHE'),
('University of Limpopo', 'University', 'Limpopo', 'https://www.ul.ac.za', 'CHE'),
('Nelson Mandela University', 'University', 'Eastern Cape', 'https://www.mandela.ac.za', 'CHE'),
('North-West University', 'University', 'North West', 'https://www.nwu.ac.za', 'CHE'),
('University of Pretoria', 'University', 'Gauteng', 'https://www.up.ac.za', 'CHE'),
('Rhodes University', 'University', 'Eastern Cape', 'https://www.ru.ac.za', 'CHE'),
('Sefako Makgatho Health Sciences University', 'University', 'Gauteng', 'https://www.smu.ac.za', 'CHE'),
('Stellenbosch University', 'University', 'Western Cape', 'https://www.sun.ac.za', 'CHE'),
('University of South Africa', 'University', 'Gauteng', 'https://www.unisa.ac.za', 'CHE'),
('University of the Western Cape', 'University', 'Western Cape', 'https://www.uwc.ac.za', 'CHE'),
('University of the Witwatersrand', 'University', 'Gauteng', 'https://www.wits.ac.za', 'CHE'),
('University of Venda', 'University', 'Limpopo', 'https://www.univen.ac.za', 'CHE'),
('Walter Sisulu University', 'University', 'Eastern Cape', 'https://www.wsu.ac.za', 'CHE'),
('Cape Peninsula University of Technology', 'University of Technology', 'Western Cape', 'https://www.cput.ac.za', 'CHE'),
('Central University of Technology', 'University of Technology', 'Free State', 'https://www.cut.ac.za', 'CHE'),
('Durban University of Technology', 'University of Technology', 'KwaZulu-Natal', 'https://www.dut.ac.za', 'CHE'),
('Mangosuthu University of Technology', 'University of Technology', 'KwaZulu-Natal', 'https://www.mut.ac.za', 'CHE'),
('Tshwane University of Technology', 'University of Technology', 'Gauteng', 'https://www.tut.ac.za', 'CHE'),
('Vaal University of Technology', 'University of Technology', 'Gauteng', 'https://www.vut.ac.za', 'CHE'),

-- Public TVET Colleges (all 50)
('Buffalo City TVET College', 'TVET', 'Eastern Cape', 'https://www.bccollege.co.za', 'DHET'),
('Eastcape Midlands TVET College', 'TVET', 'Eastern Cape', 'https://www.emcol.co.za', 'DHET'),
('Ingwe TVET College', 'TVET', 'Eastern Cape', 'https://www.ingwecollege.edu.za', 'DHET'),
('King Hintsa TVET College', 'TVET', 'Eastern Cape', 'https://www.kinghintsacollege.edu.za', 'DHET'),
('King Sabata Dalindyebo TVET College', 'TVET', 'Eastern Cape', 'https://www.ksdcollege.edu.za', 'DHET'),
('Lovedale TVET College', 'TVET', 'Eastern Cape', 'https://www.lovedalecollege.co.za', 'DHET'),
('Port Elizabeth TVET College', 'TVET', 'Eastern Cape', 'https://www.pecollege.edu.za', 'DHET'),
('Maluti TVET College', 'TVET', 'Free State', 'https://www.malutitvet.co.za', 'DHET'),
('Motheo TVET College', 'TVET', 'Free State', 'https://www.motheocollege.edu.za', 'DHET'),
('Flavius Mareka TVET College', 'TVET', 'Free State', 'https://www.fmcollege.co.za', 'DHET'),
('Goldfields TVET College', 'TVET', 'Free State', 'https://www.goldfieldstvet.edu.za', 'DHET'),
('Central Johannesburg TVET College', 'TVET', 'Gauteng', 'https://www.cjc.co.za', 'DHET'),
('Ekurhuleni East TVET College', 'TVET', 'Gauteng', 'https://www.eec.edu.za', 'DHET'),
('Ekurhuleni West TVET College', 'TVET', 'Gauteng', 'https://www.ewc.edu.za', 'DHET'),
('Sedibeng TVET College', 'TVET', 'Gauteng', 'https://www.sedcol.co.za', 'DHET'),
('South West Gauteng TVET College', 'TVET', 'Gauteng', 'https://www.swgc.co.za', 'DHET'),
('Tshwane North TVET College', 'TVET', 'Gauteng', 'https://www.tnc.edu.za', 'DHET'),
('Tshwane South TVET College', 'TVET', 'Gauteng', 'https://www.tsc.edu.za', 'DHET'),
('Western TVET College', 'TVET', 'Gauteng', 'https://www.westcol.co.za', 'DHET'),
('Coastal TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.coastalkzn.co.za', 'DHET'),
('Elangeni TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.elangeni.edu.za', 'DHET'),
('Esayidi TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.esayidi.com', 'DHET'),
('Majuba TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.majuba.edu.za', 'DHET'),
('Mnambithi TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.mnambithicollege.co.za', 'DHET'),
('Mthashana TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.mthashanacollege.co.za', 'DHET'),
('Thekwini TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.thekwinicollege.co.za', 'DHET'),
('Umfolozi TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.umfolozicollege.co.za', 'DHET'),
('Umgungundlovu TVET College', 'TVET', 'KwaZulu-Natal', 'https://www.umgungundlovu.edu.za', 'DHET'),
('Capricorn TVET College', 'TVET', 'Limpopo', 'https://www.capricorncollege.edu.za', 'DHET'),
('Lephalale TVET College', 'TVET', 'Limpopo', 'https://www.lephalaletvet.edu.za', 'DHET'),
('Letaba TVET College', 'TVET', 'Limpopo', 'https://www.letabacollege.edu.za', 'DHET'),
('Mopani South East TVET College', 'TVET', 'Limpopo', 'https://www.mopanicollege.edu.za', 'DHET'),
('Sekhukhune TVET College', 'TVET', 'Limpopo', 'https://www.sekhukhunecollege.edu.za', 'DHET'),
('Vhembe TVET College', 'TVET', 'Limpopo', 'https://www.vhembecollege.edu.za', 'DHET'),
('Waterberg TVET College', 'TVET', 'Limpopo', 'https://www.waterbergcollege.edu.za', 'DHET'),
('Gert Sibande TVET College', 'TVET', 'Mpumalanga', 'https://www.gscollege.edu.za', 'DHET'),
('Nkangala TVET College', 'TVET', 'Mpumalanga', 'https://www.nkangalacollege.edu.za', 'DHET'),
('Ehlanzeni TVET College', 'TVET', 'Mpumalanga', 'https://www.ehlanzenicollege.edu.za', 'DHET'),
('Orbit TVET College', 'TVET', 'North West', 'https://www.orbitcollege.edu.za', 'DHET'),
('Taletso TVET College', 'TVET', 'North West', 'https://www.taletso.edu.za', 'DHET'),
('Vuselela TVET College', 'TVET', 'North West', 'https://www.vuselelacollege.co.za', 'DHET'),
('Boland TVET College', 'TVET', 'Western Cape', 'https://www.bolandcollege.com', 'DHET'),
('College of Cape Town', 'TVET', 'Western Cape', 'https://www.cct.edu.za', 'DHET'),
('False Bay TVET College', 'TVET', 'Western Cape', 'https://www.falsebaycollege.co.za', 'DHET'),
('Northlink TVET College', 'TVET', 'Western Cape', 'https://www.northlink.co.za', 'DHET'),
('South Cape TVET College', 'TVET', 'Western Cape', 'https://www.sccollege.co.za', 'DHET'),
('West Coast TVET College', 'TVET', 'Western Cape', 'https://www.westcoastcollege.co.za', 'DHET'),

-- Private Higher Education Institutions (selection)
('AFDA', 'Private College', 'Multiple', 'https://www.afda.co.za', 'CHE'),
('Boston City Campus', 'Private College', 'Multiple', 'https://www.boston.co.za', 'DHET'),
('Damelin College', 'Private College', 'Multiple', 'https://www.damelin.co.za', 'DHET'),
('Richfield Graduate Institute', 'Private College', 'Multiple', 'https://www.rgit.co.za', 'DHET'),
('Varsity College', 'Private College', 'Multiple', 'https://www.varsitycollege.co.za', 'CHE'),
('IIE Rosebank College', 'Private College', 'Multiple', 'https://www.rosebankcollege.co.za', 'CHE'),
('IIE Vega School', 'Private College', 'Multiple', 'https://www.vegaschool.com', 'CHE'),
('Monash South Africa', 'Private College', 'Gauteng', 'https://www.monash.edu', 'CHE'),
('Pearson Institute of Higher Education', 'Private College', 'Multiple', 'https://www.pearsoninstitute.africa', 'CHE'),
('Regent Business School', 'Private College', 'Multiple', 'https://www.regent.ac.za', 'CHE'),
('Southern Business School', 'Private College', 'Multiple', 'https://www.sbs.ac.za', 'CHE'),
('St Augustine College', 'Private College', 'Gauteng', 'https://www.staugustine.ac.za', 'CHE'),
('Milpark Education', 'Private College', 'Multiple', 'https://www.milpark.ac.za', 'CHE'),
('Oxbridge Academy', 'Private College', 'Western Cape', 'https://www.oxbridgeacademy.edu.za', 'DHET'),
('Central Technical College', 'Private College', 'Multiple', 'https://www.ctc.edu.za', 'DHET'),
('Berea Technical College', 'Private College', 'KwaZulu-Natal', 'https://www.btc.edu.za', 'DHET'),
('Qualitas Career Academy', 'Private College', 'Multiple', 'https://www.qualitasworld.co.za', 'DHET'),
('Jeppe College', 'Private College', 'Gauteng', 'https://www.jeppecollege.co.za', 'DHET'),
('Dam Technical College', 'Private College', 'Gauteng', 'https://www.damcollege.co.za', 'DHET'),
('Centurion Academy', 'Private College', 'Gauteng', 'https://www.ca.ac.za', 'DHET'),
('Life Prep College', 'Private College', 'KwaZulu-Natal', 'https://www.lifeprepcollege.co.za', 'DHET'),
('CTU Training Solutions', 'Private College', 'Multiple', 'https://www.ctutraining.co.za', 'DHET'),
('Durbanville College', 'Private College', 'Western Cape', 'https://www.durbanvillecollege.com', 'DHET'),
('Lyceum College', 'Private College', 'Multiple', 'https://www.lyceum.co.za', 'DHET'),
('Midrand Graduate Institute', 'Private College', 'Gauteng', 'https://www.mgi.ac.za', 'CHE'),
('Prestige Academy', 'Private College', 'Western Cape', 'https://www.prestigeacademy.co.za', 'DHET'),
('Red & Yellow Creative School', 'Private College', 'Western Cape', 'https://www.redandyellow.co.za', 'CHE'),
('Rostec Technical College', 'Private College', 'Gauteng', 'https://www.rostec.co.za', 'DHET'),
('SANTS Private Higher Education Institution', 'Private College', 'Gauteng', 'https://www.sants.co.za', 'CHE'),
('Stadio Higher Education', 'Private College', 'Multiple', 'https://www.stadio.ac.za', 'CHE'),
('Trinity International Bible University', 'Private College', 'Gauteng', 'https://www.tibu.edu.za', 'CHE'),
('Academy of Digital Arts', 'Private College', 'Western Cape', 'https://www.digitalarts.co.za', 'DHET'),
('Aros School of Fashion', 'Private College', 'Gauteng', 'https://www.aros.co.za', 'DHET'),
('Durban Film School', 'Private College', 'KwaZulu-Natal', 'https://www.durbanfilmschool.co.za', 'DHET'),
('Inscape Education Group', 'Private College', 'Multiple', 'https://www.inscape.ac', 'DHET'),
('Open Learning Group', 'Private College', 'Multiple', 'https://www.olg.co.za', 'DHET'),
('South African College of Applied Psychology', 'Private College', 'Multiple', 'https://www.sacap.edu.za', 'CHE'),
('South African School of Motion Picture Medium', 'Private College', 'Western Cape', 'https://www.afda.co.za', 'CHE'),
('The Animation School', 'Private College', 'Gauteng', 'https://www.theanimationschool.co.za', 'DHET');